name: "Setup Java, dependencies and Maven cache"
description: "Set up JDK, clone and optionally compile dependencies, and configure Maven cache using a key that includes dependencies_sha"

inputs:
  java_version:
    description: "Java version to use"
    required: false
    default: "8"
  storage_hadoop:
    description: "Hadoop flavour, used as part of the Maven cache key"
    required: false
    default: "hdi5.1"
  dependency_repos:
    description: "Comma-separated list of dependency repositories (e.g. 'java-common-libs,biodata,cellbase')"
    required: false
    default: ""
  require_cache_hit:
    description: "If true, fail the job when the Maven cache is not found for the current dependencies_sha"
    required: false
    default: "false"
  needs_hadoop_preparation:
    description: "If true, prepare Hadoop environment after setting up Java and Maven cache"
    required: false
    default: "false"
  deploy_maven:
    description: "If true, configure Java and Maven for deploy (GPG, Nexus, etc)"
    required: false
    default: "false"
  server-username:
    description: "Username for Maven deploy (Nexus)"
    required: false
    default: ""  # env variable for username in deploy
  server-password:
    description: "Password/token for Maven deploy (Nexus)"
    required: false
    default: ""  # env variable for token in deploy
  gpg-private-key:
    description: "GPG private key for Maven deploy"
    required: false
    default: ""   # Value of the GPG private key to import
  gpg-passphrase:
    description: "GPG passphrase for Maven deploy"
    required: false
    default: ""

outputs:
  dependencies_sha:
    description: "Hash that represents dependency commits (OpenCGA/java-common-libs/biodata/cellbase, etc.)"
    value: ${{ steps.clone_dependencies.outputs.dependencies_sha }}
  cache-hit:
    description: "True if the Maven cache key with this dependencies_sha was already present"
    value: ${{ steps.maven_cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      if: ${{ inputs.dependency_repos != '' }}
      name: Checkout ci-core repository
      id: "checkout-ci-core"
      ## This checkout pulls the code of the ci-core repository to get the scripts
      ## Checkout to "ci-core" folder.
      ## Filter by ".github" folder
      with:
        repository: opencb/ci-core
        ref: main
        path: ci-core
        fetch-depth: '1'
    - name: Set up JDK
      if: ${{ inputs.deploy_maven != 'true' }}
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java_version }}
    - name: Set up JDK for deploy
      if: ${{ inputs.deploy_maven == 'true' }}
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: ${{ inputs.java_version }}
        cache: 'maven'
        server-id: ossrh
        server-username: ${{ inputs.server-username }}
        server-password: ${{ inputs.server-password }}
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: ${{ inputs.gpg-passphrase }}
    - name: Clone dependencies and compute dependencies_sha
      id: clone_dependencies
      if: ${{ inputs.dependency_repos != '' }}
      shell: bash
      run: |
        # This step clones the dependency repositories using the helper script
        # and computes a stable dependencies_sha based on all dependency commits.
        #
        # It expects get_same_branch.sh to:
        #   - clone or checkout each repo on the same branch as the caller
        #   - update DEPENDENCIES_SHA in-place
        #   - finally write `dependencies_sha=<hash>` into $GITHUB_OUTPUT

        if [ -f "ci-core/.github/workflows/scripts/get_same_branch.sh" ]; then
          chmod +x ci-core/.github/workflows/scripts/get_same_branch.sh

          # Initialize DEPENDENCIES_SHA with the current repo SHA so that
          # main project changes also affect the final cache key.
          export DEPENDENCIES_SHA="${{ github.sha }}"
          export WORKSPACE="workspace"

          ci-core/.github/workflows/scripts/get_same_branch.sh \
            "${{ github.ref_name }}" \
            "${{ inputs.dependency_repos }}"
        else
          echo "get_same_branch.sh script not found. Skipping dependency checkout."
          # Fallback: use only the current repo SHA as dependencies_sha
          DEPENDENCIES_SHA="${{ github.sha }}"
          echo "dependencies_sha=${DEPENDENCIES_SHA}" >> "$GITHUB_OUTPUT"
        fi

    - name: Cache local Maven repository
      id: maven_cache
      # This step restores and saves the Maven local repository cache, using
      # storage_hadoop and dependencies_sha as part of the cache key.
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ inputs.storage_hadoop }}-${{ steps.clone_dependencies.outputs.dependencies_sha || github.sha }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ inputs.storage_hadoop }}-
        ## Force cache hit to avoid analyzing with incomplete dependencies
        fail-on-cache-miss: ${{ inputs.require_cache_hit }}
    - name: Compile dependencies (only if cache did not hit)
      if: ${{ inputs.dependency_repos != '' && steps.maven_cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        # This step compiles dependency repositories only when the Maven cache
        # for the current dependencies_sha was not found.
        #
        # It expects compile_same_branch.sh to:
        #   - iterate over the comma-separated dependency_repos list
        #   - run `mvn clean install -DskipTests` on each dependency
        #   - populate ~/.m2/repository with the latest built artifacts

        if [ -f "ci-core/.github/workflows/scripts/compile_same_branch.sh" ]; then
          chmod +x ci-core/.github/workflows/scripts/compile_same_branch.sh
          export WORKSPACE="workspace"
          ci-core/.github/workflows/scripts/compile_same_branch.sh "${{ inputs.dependency_repos }}"
        else
          echo "compile_same_branch.sh script not found. Skipping dependency compilation."
        fi
    - name: Prepare Hadoop profile
      if: ${{ inputs.needs_hadoop_preparation == 'true' }}
      shell: bash
      run: |
        chmod +x ci-core/.github/workflows/scripts/prepare_hadoop.sh
        ci-core/.github/workflows/scripts/prepare_hadoop.sh --hadoop-flavour "${{ inputs.storage_hadoop }}"
      env:
        THIRDPARTY_READ_TOKEN: ${{ env.THIRDPARTY_READ_TOKEN }}
    - name: Cache summary
      # This step writes a small summary into the GitHub job summary, so it is
      # easy to inspect which dependencies_sha and cache key were used.
      shell: bash
      run: |
        {
          echo "## Java / Maven cache summary"
          echo ""
          echo "- Java version: \`${{ inputs.java_version }}\`"
          echo "- Dependencies sha: \`${{ steps.clone_dependencies.outputs.dependencies_sha || 'No dependencies' }}\`"
          echo "- Prepare Hadoop environment: \`${{ inputs.needs_hadoop_preparation }}\`"
          echo "- Maven cache key: \`${{ runner.os }}-maven-${{ inputs.storage_hadoop }}-${{ steps.clone_dependencies.outputs.dependencies_sha }}\`"
          echo "- Maven cache hit: \`${{ steps.maven_cache.outputs.cache-hit || 'false' }}\`"
        } >> "$GITHUB_STEP_SUMMARY"
