name: "Test summary"
description: "Generate a Markdown summary of Surefire test results and write it to GITHUB_STEP_SUMMARY"

inputs:
  report_paths:
    description: "Glob pattern for Surefire XML reports"
    required: false
    default: "./**/surefire-reports/TEST-*.xml"
  title:
    description: "Title for the test summary section"
    required: false
    default: "Test summary"
  include_module_table:
    description: "Whether to include the per-module breakdown table"
    required: false
    default: "true"

outputs:
  total_success:
    description: "Total number of successful tests"
    value: ${{ steps.generate_summary.outputs.total_success }}
  total_failed:
    description: "Total number of failed tests"
    value: ${{ steps.generate_summary.outputs.total_failed }}
  total_errors:
    description: "Total number of tests with errors"
    value: ${{ steps.generate_summary.outputs.total_errors }}
  total_skipped:
    description: "Total number of skipped tests"
    value: ${{ steps.generate_summary.outputs.total_skipped }}
  total_tests:
    description: "Total number of tests"
    value: ${{ steps.generate_summary.outputs.total_tests }}

runs:
  using: "composite"
  steps:
    - name: Generate test summary
      id: generate_summary
      shell: bash
      env:
        REPORT_GLOB: ${{ inputs.report_paths }}
        SUMMARY_TITLE: ${{ inputs.title }}
        INCLUDE_MODULE_TABLE: ${{ inputs.include_module_table }}
      run: |
        # Use Python to parse Surefire XML reports and generate a Markdown summary
        python - << 'PY'
        import glob
        import os
        import xml.etree.ElementTree as ET
        import sys

        report_glob = os.environ.get("REPORT_GLOB", "./**/surefire-reports/TEST-*.xml")
        title = os.environ.get("SUMMARY_TITLE", "Test summary")
        include_module_table = os.environ.get("INCLUDE_MODULE_TABLE", "true").lower() == "true"
        github_step_summary = os.environ.get("GITHUB_STEP_SUMMARY")
        github_output = os.environ.get("GITHUB_OUTPUT")

        # Collect all report files
        report_files = glob.glob(report_glob, recursive=True)

        # Data structures for totals and per-module aggregation
        total = {
            "tests": 0,
            "failures": 0,
            "errors": 0,
            "skipped": 0,
        }
        modules = {}

        def update_counts(target, tests, failures, errors, skipped):
          target["tests"] += tests
          target["failures"] += failures
          target["errors"] += errors
          target["skipped"] += skipped

        for path in report_files:
          try:
            tree = ET.parse(path)
            root = tree.getroot()
          except Exception as e:
            # Skip malformed XML files
            continue

          # Surefire can be <testsuite> or <testsuites> root
          suites = []
          if root.tag == "testsuite":
            suites = [root]
          elif root.tag == "testsuites":
            suites = list(root.findall("testsuite"))

          if not suites:
            continue

          # Deduce module name from path (dir before 'target')
          # Example: some-module/target/surefire-reports/TEST-*.xml -> module = 'some-module'
          parts = path.split(os.sep)
          module_name = "root"
          if "target" in parts:
            idx = parts.index("target")
            if idx > 0:
              module_name = parts[idx - 1]

          if module_name not in modules:
            modules[module_name] = {
              "tests": 0,
              "failures": 0,
              "errors": 0,
              "skipped": 0,
            }

          for suite in suites:
            def get_int(attr_name):
              value = suite.attrib.get(attr_name, "0")
              try:
                return int(value)
              except ValueError:
                return 0

            tests = get_int("tests")
            failures = get_int("failures")
            errors = get_int("errors")
            skipped = get_int("skipped")

            update_counts(total, tests, failures, errors, skipped)
            update_counts(modules[module_name], tests, failures, errors, skipped)

        # Compute derived values
        def compute_success(data):
          return max(0, data["tests"] - data["failures"] - data["errors"] - data["skipped"])

        total_success = compute_success(total)

        # Build Markdown summary
        lines = []

        lines.append(f"## {title}")
        lines.append("")
        if not report_files:
          lines.append("_No test reports were found with pattern:_")
          lines.append(f"`{report_glob}`")
        else:
          # Overall table
          lines.append("### Overall")
          lines.append("")
          lines.append("| Success | Failed | Errors | Skipped | Total |")
          lines.append("| --- | --- | --- | --- | --- |")
          lines.append(
            f"| {total_success} | {total['failures']} | {total['errors']} | {total['skipped']} | {total['tests']} |"
          )
          lines.append("")

          if include_module_table and modules:
            lines.append("### By module")
            lines.append("")
            lines.append("| Module | Success | Failed | Errors | Skipped | Total |")
            lines.append("| --- | --- | --- | --- | --- | --- |")
            for module_name in sorted(modules.keys()):
              data = modules[module_name]
              success = compute_success(data)
              lines.append(
                f"| {module_name} | {success} | {data['failures']} | {data['errors']} | {data['skipped']} | {data['tests']} |"
              )
            lines.append("")

          # Optional detail: number of XML report files found
          lines.append(f"_Processed {len(report_files)} Surefire report file(s)._")

        markdown = "\n".join(lines)

        # Write to step summary if available
        if github_step_summary:
          with open(github_step_summary, "a", encoding="utf-8") as f:
            f.write(markdown + "\n")

        # Write outputs for reuse
        if github_output:
          def write_output(name, value):
            with open(github_output, "a", encoding="utf-8") as f:
              f.write(f"{name}={value}\n")

          write_output("total_success", total_success)
          write_output("total_failed", total["failures"])
          write_output("total_errors", total["errors"])
          write_output("total_skipped", total["skipped"])
          write_output("total_tests", total["tests"])
        PY
